language: cpp
git:
  depth: false
addons:
  apt:
    packages:
      - hwloc
      - libhwloc-dev
  homebrew:
    packages:
      - hwloc
      - libomp
    update: true
before_install:
  - cwd=$(pwd)
  - cd /tmp
  - git clone https://github.com/kokkos/kokkos.git
  - mkdir build_kokkos
  - mkdir install_kokkos
  - cd build_kokkos
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake ../kokkos  -DKokkos_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/tmp/install_kokkos -DKokkos_ENABLE_OPENMP=On -DKokkos_ENABLE_HWLOC=On; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake ../kokkos -DKokkos_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/tmp/install_kokkos -DKokkos_ENABLE_OPENMP=On -DKokkos_ENABLE_HWLOC=On; fi
  - make install
  - cd ${cwd}
script: 
  - make 
jobs:
  include:
      - name: "linux gcc release"
        os: linux
        dist: bionic
        compiler: gcc
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
      - name: "macos release"
        os: osx
        osx_image: xcode10.2
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
      - name: "linux clang release"
        os: linux
        dist: bionic
        compiler: clang
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
      - name: "linux gcc debug"
        os: linux
        dist: bionic
        compiler: gcc
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
      - name: "linux clang debug"
        os: linux
        dist: bionic
        compiler: clang
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
