os: 
  - linux
  - osx
dist: bionic
language: cpp
git:
  depth: false
before_install:
  - cwd=$(pwd)
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install hwloc libhwloc-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install hwloc libhwloc-dev; fi
  - cd /tmp
  - git clone https://github.com/kokkos/kokkos.git
  - mkdir build_kokkos
  - mkdir install_kokkos
  - cd build_kokkos
  - cmake ../kokkos -DKokkos_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/tmp/install_kokkos -DKokkos_ENABLE_OPENMP=On -DKokkos_ENABLE_HWLOC=On
  - make install
  - cd ${cwd}
script: 
  - make 
jobs:
  include:
      - name: "gcc release"
        compiler:
          - gcc
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
      - name: "clang release"
        compiler:
          - clang
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
      - name: "gcc debug"
        compiler:
          - gcc
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
      - name: "clang debug"
        compiler:
          - clang
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 