language: cpp
git:
  depth: false
addons:
  apt:
    packages:
<<<<<<< HEAD
      - clang-format
=======
      - clang-format-diff
>>>>>>> ea126ad6d0a7733d5381de3628499ebd67a74d3b
      - hwloc
      - libhwloc-dev
  homebrew:
    packages:
      - hwloc
    update: true
before_install:
  - cwd=$(pwd)
  - cd /tmp
  - git clone https://github.com/kokkos/kokkos.git
  - mkdir build_kokkos
  - mkdir install_kokkos
  - cd build_kokkos
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then cmake ../kokkos  -DKokkos_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/tmp/install_kokkos -DKokkos_ENABLE_OPENMP=Off -DKokkos_ENABLE_HWLOC=On; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cmake ../kokkos -DKokkos_CXX_STANDARD=17 -DCMAKE_INSTALL_PREFIX=/tmp/install_kokkos -DKokkos_ENABLE_OPENMP=On -DKokkos_ENABLE_HWLOC=On; fi
  - make install
  - cd ${cwd}
jobs:
  include:
      - stage: "Pre-check"
        name: "formatting"
        os: linux
        dist: bionic
        script: ./check_format.sh
      - stage: "Compilation"
        name: "linux gcc release"
        os: linux
        dist: bionic
        compiler: gcc
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
        script: 
          - make -j 4 
      - stage: "Compilation"
        name: "macos release"
        os: osx
        osx_image: xcode11.5
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
        script: 
          - make -j 4 
      - stage: "Compilation"
        name: "linux clang release"
        os: linux
        dist: bionic
        compiler: clang
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
        script: 
          - make -j 4 
      - stage: "Compilation"
        name: "linux gcc debug"
        os: linux
        dist: bionic
        compiler: gcc
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
        script: 
          - make -j 4 
      - stage: "Compilation"
        name: "linux clang debug"
        os: linux
        dist: bionic
        compiler: clang
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
        script: 
          - make -j 4
      - stage: "Integration tests"
        name: "linux gcc release"
        # Here we compile again the source. There is maybe a way to use previous executable...
        os: linux
        dist: bionic
        compiler: gcc
        before_script:
          # create a build folder for the out-of-source build
          - mkdir build
          # switch to build directory
          - cd build
          # run cmake; here we assume that the project's
          # top-level CMakeLists.txt is located at '..'
          - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_VERBOSE_MAKEFILE=ON -DKOKKOS_INSTALL_PATH=/tmp/install_kokkos .. 
          - make -j 4 
        script:
          - ctest -j 4
stages:
  - "Pre-check"
  - "Compilation"
  - "Integration tests"
